# netlify.toml
[build]
  base = ""  # My base directory
  publish = "backend/" 
  command = "node backend/server.js"  # Replace with your backend build command
  #command = "npm run build && node backend/server.js"
  #functions = "backend/"  # Path to the backend build output directory


[functions]
  directory = "netlify/functions"
  #external_node_modules = ["express"]
  #node_bundler = "esbuild"
  included_files = ["backend/build/static/js/*.js","backend/build/image/*.jpg","backend/build/index.html"]

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/.netlify/functions/api/:splat"